name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and update code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd LocalNodeVS
            git pull origin main  # Pull the latest changes from the main branch
            sudo pkill node  # Stop the running Node.js process
            screen -d -m npm start  # Restart the Node.js application in detached mode with screen
